version: "3.9"

services:
  haraka:
    build:
      dockerfile: Dockerfile
    environment:
      - AUTH_URL=http://host.docker.internal/api/haraka/mailtrap-auth
      - INBOUND_MAIL_URL=http://host.docker.internal/api/haraka/mail-trap
      - API_TOKEN=abc123
    volumes:
      - ./:/app
    image: 'haraka'
    ports:
      - "25:25"
