# This file can be used for development purposes
services:
  haraka:
    build:
      dockerfile: Dockerfile
    environment:
      AUTH_URL: '${WWWUSER}'
      INBOUND_MAIL_URL: '${INBOUND_MAIL_URL}'
      API_TOKEN: '${API_TOKEN}'
    volumes:
      - ./:/app
    image: 'haraka'
    ports:
      - "25:25"
